package ro.pub.cti.jokes.db;
// Generated Apr 11, 2014 12:08:35 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String url;
     private Set subcategories = new HashSet(0);

    public Category() {
    }

    public Category(String name, String url, Set subcategories) {
       this.name = name;
       this.url = url;
       this.subcategories = subcategories;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Set getSubcategories() {
        return this.subcategories;
    }
    
    public void setSubcategories(Set subcategories) {
        this.subcategories = subcategories;
    }




}


