package ro.pub.cti.jokes.db;
// Generated Apr 11, 2014 12:08:35 AM by Hibernate Tools 3.6.0



/**
 * Comment generated by hbm2java
 */
public class Comment  implements java.io.Serializable {


     private Integer id;
     private String timestamp;
     private Joke joke;
     private String content;
     private String author;

    public Comment() {
    }

    public Comment(Joke joke, String content, String author) {
       this.joke = joke;
       this.content = content;
       this.author = author;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }
    public Joke getJoke() {
        return this.joke;
    }
    
    public void setJoke(Joke joke) {
        this.joke = joke;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }




}


