package ro.pub.cti.jokes.db;
// Generated Apr 11, 2014 12:08:35 AM by Hibernate Tools 3.6.0



/**
 * JokeCategory generated by hbm2java
 */
public class JokeCategory  implements java.io.Serializable {


     private Integer id;
     private Joke joke;
     private Subcategory subcategory;

    public JokeCategory() {
    }

    public JokeCategory(Joke joke, Subcategory subcategory) {
       this.joke = joke;
       this.subcategory = subcategory;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Joke getJoke() {
        return this.joke;
    }
    
    public void setJoke(Joke joke) {
        this.joke = joke;
    }
    public Subcategory getSubcategory() {
        return this.subcategory;
    }
    
    public void setSubcategory(Subcategory subcategory) {
        this.subcategory = subcategory;
    }




}


