package ro.pub.cti.jokes.db;
// Generated Apr 11, 2014 12:08:35 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Subcategory generated by hbm2java
 */
public class Subcategory  implements java.io.Serializable {


     private Integer id;
     private Category category;
     private String name;
     private String url;
     private Set jokeCategories = new HashSet(0);

    public Subcategory() {
    }

	
    public Subcategory(Category category) {
        this.category = category;
    }
    public Subcategory(Category category, String name, String url, Set jokeCategories) {
       this.category = category;
       this.name = name;
       this.url = url;
       this.jokeCategories = jokeCategories;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Set getJokeCategories() {
        return this.jokeCategories;
    }
    
    public void setJokeCategories(Set jokeCategories) {
        this.jokeCategories = jokeCategories;
    }




}


