package ro.pub.cti.jokes.analyzer.db;
// Generated Apr 9, 2014 12:57:16 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
public class Categories  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String url;
     private Set subcategorieses = new HashSet(0);

    public Categories() {
    }

    public Categories(String name, String url, Set subcategorieses) {
       this.name = name;
       this.url = url;
       this.subcategorieses = subcategorieses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Set getSubcategorieses() {
        return this.subcategorieses;
    }
    
    public void setSubcategorieses(Set subcategorieses) {
        this.subcategorieses = subcategorieses;
    }




}


