package ro.pub.cti.jokes.analyzer.db;
// Generated Apr 9, 2014 12:57:16 AM by Hibernate Tools 3.6.0



/**
 * Comments generated by hbm2java
 */
public class Comments  implements java.io.Serializable {


     private Integer id;
     private String timestamp;
     private Jokes jokes;
     private String content;
     private String author;

    public Comments() {
    }

    public Comments(Jokes jokes, String content, String author) {
       this.jokes = jokes;
       this.content = content;
       this.author = author;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }
    public Jokes getJokes() {
        return this.jokes;
    }
    
    public void setJokes(Jokes jokes) {
        this.jokes = jokes;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }




}


