package ro.pub.cti.jokes.analyzer.db;
// Generated Apr 9, 2014 12:57:16 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Jokes generated by hbm2java
 */
public class Jokes  implements java.io.Serializable {


     private Integer id;
     private String title;
     private String content;
     private Float rating;
     private Integer votes;
     private Integer likes;
     private String url;
     private Integer commentsCount;
     private Set commentses = new HashSet(0);
     private Set jokesCategorieses = new HashSet(0);

    public Jokes() {
    }

    public Jokes(String title, String content, Float rating, Integer votes, Integer likes, String url, Integer commentsCount, Set commentses, Set jokesCategorieses) {
       this.title = title;
       this.content = content;
       this.rating = rating;
       this.votes = votes;
       this.likes = likes;
       this.url = url;
       this.commentsCount = commentsCount;
       this.commentses = commentses;
       this.jokesCategorieses = jokesCategorieses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Float getRating() {
        return this.rating;
    }
    
    public void setRating(Float rating) {
        this.rating = rating;
    }
    public Integer getVotes() {
        return this.votes;
    }
    
    public void setVotes(Integer votes) {
        this.votes = votes;
    }
    public Integer getLikes() {
        return this.likes;
    }
    
    public void setLikes(Integer likes) {
        this.likes = likes;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Integer getCommentsCount() {
        return this.commentsCount;
    }
    
    public void setCommentsCount(Integer commentsCount) {
        this.commentsCount = commentsCount;
    }
    public Set getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set commentses) {
        this.commentses = commentses;
    }
    public Set getJokesCategorieses() {
        return this.jokesCategorieses;
    }
    
    public void setJokesCategorieses(Set jokesCategorieses) {
        this.jokesCategorieses = jokesCategorieses;
    }




}


