package ro.pub.cti.jokes.analyzer.db;
// Generated Apr 9, 2014 12:57:16 AM by Hibernate Tools 3.6.0



/**
 * JokesCategories generated by hbm2java
 */
public class JokesCategories  implements java.io.Serializable {


     private Integer id;
     private Jokes jokes;
     private Subcategories subcategories;

    public JokesCategories() {
    }

    public JokesCategories(Jokes jokes, Subcategories subcategories) {
       this.jokes = jokes;
       this.subcategories = subcategories;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Jokes getJokes() {
        return this.jokes;
    }
    
    public void setJokes(Jokes jokes) {
        this.jokes = jokes;
    }
    public Subcategories getSubcategories() {
        return this.subcategories;
    }
    
    public void setSubcategories(Subcategories subcategories) {
        this.subcategories = subcategories;
    }




}


