package ro.pub.cti.jokes.analyzer.db;
// Generated Apr 9, 2014 12:57:16 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Subcategories generated by hbm2java
 */
public class Subcategories  implements java.io.Serializable {


     private Integer id;
     private Categories categories;
     private String name;
     private String url;
     private Set jokesCategorieses = new HashSet(0);

    public Subcategories() {
    }

	
    public Subcategories(Categories categories) {
        this.categories = categories;
    }
    public Subcategories(Categories categories, String name, String url, Set jokesCategorieses) {
       this.categories = categories;
       this.name = name;
       this.url = url;
       this.jokesCategorieses = jokesCategorieses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Set getJokesCategorieses() {
        return this.jokesCategorieses;
    }
    
    public void setJokesCategorieses(Set jokesCategorieses) {
        this.jokesCategorieses = jokesCategorieses;
    }




}


